name: menskopp
favicon: null
layout_spectrum: 0.6726429555565119
typography_spectrum: 0.8218547047581524
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.20613808743655682
  lightness: 0.7677068749908358
  saturation: 0.6912351979408413
  rhythmicContrast: 0.964496647939086
purpose: []
